name: Publish Timing Android App

#on:
#  release:
#    types: [published]
 on:
   workflow_dispatch: # Run manually

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Create secrets.release.json
        run: |
          @echo off
          echo { > secrets.release.json
          echo   "Keycloak": { >> secrets.release.json
          echo     "Realm": "${{ vars.KEYCLOAKREALM }}", >> secrets.release.json
          echo     "ClientId": "${{ secrets.KC_ANDROID_CLIENT_ID }}", >> secrets.release.json
          echo     "ClientSecret": "${{ secrets.KC_ANDROID_CLIENT_SECRET }}" >> secrets.release.json
          echo   } >> secrets.release.json
          echo } >> secrets.release.json
        shell: cmd

      - name: Extract SharedVersion from Directory.Build.props
        shell: pwsh
        run: |
          [xml]$xml = Get-Content Directory.Build.props
          $version = $xml.Project.PropertyGroup | Where-Object { $_.SharedVersion } | Select-Object -ExpandProperty SharedVersion
          echo "SharedVersion=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Compute AndroidVersionCode
        shell: pwsh
        run: |
          $version = "${{ env.SharedVersion }}"
          $code = ($version -replace '\.', '') -as [int]
          echo "AndroidVersionCode=$code" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Echo version values
        shell: pwsh
        run: |
          Write-Host "SharedVersion: $env:SharedVersion"
          Write-Host "AndroidVersionCode: $env:AndroidVersionCode"

      - name: Decode Keystore
        shell: pwsh
        run: |
          [IO.File]::WriteAllBytes("${{ github.workspace }}\release.keystore", [Convert]::FromBase64String("${{ secrets.ANDROID_KEYSTORE_BASE64 }}"))

      - name: Decode Play Store service account
        shell: pwsh
        run: |
          Set-Content -Path service_account.json -Value '${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}' -Encoding UTF8

      - name: Update AndroidManifest.xml version
        shell: pwsh
        run: |
          $manifestPath = "RedMist.Timing.UI.Android/Properties/AndroidManifest.xml"
          [xml]$xml = Get-Content $manifestPath

          $manifest = $xml.manifest
          $manifest.SetAttribute("android:versionCode", $env:AndroidVersionCode)
          $manifest.SetAttribute("android:versionName", $env:AndroidVersionCode)

          $xml.Save($manifestPath)

      - name: Build and sign AAB
        run: dotnet publish RedMist.Timing.UI.Android/RedMist.Timing.UI.Android.csproj -c Release -f net9.0-android /p:AndroidPackageFormat=aab /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=${{ github.workspace }}\release.keystore /p:AndroidSigningStorePass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} /p:AndroidSigningKeyAlias=${{ secrets.ANDROID_KEY_ALIAS }} /p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }} -o ${{ github.workspace }}\publish-output 

      - name: List publish-output contents
        shell: pwsh
        run: Get-ChildItem -Path ${{ github.workspace }}\publish-output -Recurse | Format-List FullName

      - name: Upload AAB to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.bigmissionmotorsports.redmist
          releaseFiles: publish-output/com.bigmissionmotorsports.redmist-Signed.aab
          track: internal
          status: completed

      